## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url = jdbc:cloudspanner:/projects/my-project/instances/my-instance/databases/my-db
spring.datasource.driver-class-name = com.google.cloud.spanner.jdbc.JdbcDriver


## Hibernate Properties

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = com.google.cloud.spanner.hibernate.SpannerDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update